development:
  adapter: postgresql
  encoding: unicode
  database: myflix_dev
  host: localhost
  pool: 5
  username: <%= ENV["MFUSER"] %>
  password: <%= ENV["MFPASSWORD"] %>

test:
  adapter: postgresql
  encoding: unicode
  database: myflix_test
  host: localhost
  pool: 5
  username: <%= ENV["MFUSER"] %>
  password: <%= ENV["MFPASSWORD"] %>
