development:
  adapter: postgresql
  encoding: unicode
  database: myflix_dev
  host: localhost
  pool: 5
  username: <%= ENV["TA_DEV"] %>
  password: <%= ENV["TA_PWD"] %>

test:
  adapter: postgresql
  encoding: unicode
  database: myflix_test
  host: localhost
  pool: 5
  username: <%= ENV["TA_DEV"] %>
  password: <%= ENV["TA_PWD"] %>
